### ISSUE TITLE
500 on signup

### ISSUE THREAD

**Issue by biggless** [ossfriday/ossfriday#139] opened 2017-08-15 21:12 UTC
Getting 500 error on github oauth callback when trying to sign up.

https://opensourcefriday.com/users/auth/github/callback?browser_session_id=SKIPPED&state=SKIPPED
![2017-08-16 00 08 51](https://user-images.githubusercontent.com/696810/29336711-5f94f8e0-8217-11e7-997a-193c7db30ddb.png)

**Comment by 178inaba** [comment] 2017-08-16 14:59
I also tried to sign in, I got a 500 error and confirmed that I can not sign in.
I read the README and launched ossfriday locally and checked whether the same error occurred, but in the local environment 500 error did not occur and I signed in successfully.

**Comment by biggless** [comment] 2017-08-16 15:02
Same result here.

**Comment by MikeMcQuaid** [comment] 2017-08-17 19:34
Forgot to run the migration when deploying https://github.com/ossfriday/ossfriday/pull/138 because I'm an idiot. Fixed now, thanks for the report, all.

**Closed by MikeMcQuaid** 2017-08-17 19:34 UTC
